version: "3.7"

services: 
  mariadb:
    image: mariadb_customer:1.0.0
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: password
    ports: 
      - 3306:3306
  customer_app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 8080:8080
    depends_on:
      - mariadb
